name: CICD
on:
  push:
    branches: [main]
    paths-ignore: ["**.md"]
  pull_request:
    paths-ignore: ["**.md"]

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Run tests and checks
    if: startsWith(github.head_ref, 'release/')
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v6

      - name: Setup | Python
        id: setup-python
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: false

      - name: Setup | Fontforge
        run: |
          sudo apt update -yq
          sudo apt install fontforge -yq

      - name: Setup | Nerdfonts
        run: |
          wget https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/FontPatcher.zip
          unzip -d nerd FontPatcher.zip

      - name: Setup | Python dependencies
        run: uv sync

      - name: Build | Build fonts
        run: fontforge -script build.py ttf

      - name: Build | Build nerdfonts
        run: fontforge -script nerd/font-patcher --complete --mono --boxdrawing -out build/TTF-NF build/TTF/*

      - name: Post Build | Pack fonts
        id: pack
        run: |
          (cd build/TTF;    cp ../../LICENSE .; 7z a ../Baccano.zip    LICENSE *.ttf)
          (cd build/TTF-NF; cp ../../LICENSE .; 7z a ../Baccano-NF.zip LICENSE *.ttf)
          echo name="Baccano.zip" >>$GITHUB_OUTPUT

      - name: Post Build | Generate checksums
        run: |
          openssl dgst -sha256 -r '${{ steps.pack.outputs.name }}' |
            cut -d' ' -f1 >'${{ steps.pack.outputs.name }}.sha256'

      - name: Pre Release | Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: ${{ needs.metadata.outputs.name }}
          path: |
            ${{ steps.pack.outputs.name }}
            ${{ steps.pack.outputs.name }}.sha256

  # How to create a new GitHub release?
  # 1. Create a release branch named "release/<tag>".
  # 2. Open a PR from the branch, including the release note in the PR body.
  # 3. Wait for the CI to create a draft release.
  # 4. Publish the release when it's ready.
  release:
    name: Create GitHub release
    needs: [build, changelog]
    if: startsWith(github.head_ref, 'release/')
    permissions:
      contents: write # need to update release
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v6

      - name: Setup | Configure
        id: configure
        run: |
          echo tag="${GITHUB_HEAD_REF#release/}" >$GITHUB_OUTPUT

      - name: Setup | Download artifacts
        uses: actions/download-artifact@v7
        with:
          path: build/
          pattern: ${{ needs.metadata.outputs.name }}

      - name: Release | Create Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          release_tag: ${{ steps.configure.outputs.tag }}
          release_body: ${{ github.event.pull_request.body }}
        run: |
          if gh release view "$release_tag" >/dev/null; then
            echo "update existing release $release_tag"
            gh release edit "$release_tag" --notes="$release_body"
          else
            echo "create new release $release_tag"
            gh release create "$release_tag" \
              --target="$GITHUB_BASE_REF" \
              --draft=true \
              --title="${release_tag#v} ($(date -u +'%Y-%m-%d'))" \
              --notes="$release_body"
          fi

      - name: Release | Upload artifacts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          release_tag: ${{ steps.configure.outputs.tag }}
        run: gh release upload --clobber "$release_tag" build/*
